### ISSUE TITLE
Clarify what this milestone is supposed to mean...

### ISSUE THREAD

**Issue by eichmann** [data2health/scits-platform#16]

**Comment by mellybelly** [comment]
I think we should have documentation of how the data ingest is performed and any model matching or cleaning that is performed. Its sort of a magic black box at present.

**Comment by eichmann** [comment]
We're actually submitting a paper next week about the information architecture, including ingest and access mechanisms!

**Comment by eichmann** [comment]
The plan for the "warehouse" is to create descriptions of available data, structure, access mechanisms as the wiki for the project repository and use it both as documentation and as a library of use examples (GraphQL queries, etc.)

**Comment by mellybelly** [comment]
great, can i help in any way? 
Also, can you please edit the milestone and include the appropriate date? thanks!

**Comment by eichmann** [comment]
Clarifications mapped into the milestone description.
